### ISSUE TITLE
Release template as NuGet package?

### ISSUE THREAD

**Issue by sergey-tihon** [MNie/FSharpNetCoreWebApiTemplate#1]
Do not you want to release this template as NuGet package for `dotnet new`?

as register it here https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

**Comment by MNie** [comment]
@sergey-tihon good idea!

**Comment by MNie** [comment]
[Nuget package released](https://www.nuget.org/packages/WebAPI.FSharp.Template/).
[Available templates updated](https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new)
Nuget badge added to readme and also readme updated :)

**Comment by sergey-tihon** [comment]
Cool! 😎
