### ISSUE TITLE
Installation Fails due to NuGet Incompatabilities

### ISSUE THREAD

**Issue by ssimontis** [MNie/FSharpNetCoreWebApiTemplate#4]
I jut tried to install this on my Windows 10 machine running VS 2019 and DotNet Core 3 Preview 6. I receive the following errors. It appears some packages are no longer available and the dependency tree needs an update.

 dotnet new -i WebAPI.FSharp.Template::*

> C:\Users\ssimo\.templateengine\dotnetcli\v3.0.100-preview6-012264\scratch\restore.csproj : error NU1102: Unable to find package Microsoft.DotNet.Watcher.Tools with version (>= 2.1.0 && < 2.2.0)

> C:\Users\ssimo\.templateengine\dotnetcli\v3.0.100-preview6-012264\scratch\restore.csproj : error NU1102:   - Found 16 version(s) in nuget.org [ Nearest version: 2.0.2 ]

> C:\Users\ssimo\.templateengine\dotnetcli\v3.0.100-preview6-012264\scratch\restore.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages`

> C:\Users\ssimo\.templateengine\dotnetcli\v3.0.100-preview6-012264\scratch\restore.csproj : error NU1102:   - Found 0 version(s) in C:\Program Files\dotnet\sdk\NuGetFallbackFolder

`  Restore failed in 2.61 sec for C:\Users\ssimo\.templateengine\dotnetcli\v3.0.100-preview6-012264\scratch\restore.csproj.`

**Comment by MNie** [comment]
Hi @ssimontis yup it is a bug it should point to [2.0, 2.1] I will fix that today and release a new version.

**Comment by ssimontis** [comment]
@MNie 	Thanks mate, I appreciate the quick turnaround and respect how quickly you were able to address the issue.

I'll test it out once new version is released.

This is off-topic, but I am trying to get more involved with F# and OSS as a whole, is there anything within the repo you need assistance with? It's pretty self-documenting so I don't see the need to create a Wiki, but I might open some issues for feature requests that I can contribute if there's nothing specific you envision as the next step for the project.

**Comment by MNie** [comment]
@ssimontis I released new version yesterday, could you give it a try?

Fantastic that you want to be involved in F# OOS, but I think there isn't a lot to do here since it is only a simple template for a web API. But for sure you could check (upforgrabs)[https://up-for-grabs.net/#/]. You could ask on FSharp slack channel if there are some projects where you could help a little bit. From my perspective, I could recommend Expecto, FsCheck, SAFE Stack, Suave, Giraffe but I don't know if there are some issues to grab ;)

**Comment by ssimontis** [comment]
@MNie 	It works! Thank you and that you for the guidance!
